[package]
name = "drogue-embedded-timer"
version = "0.1.0"
authors = ["Bob McWhirter <bmcwhirt@redhat.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Macro to shim heterogeneous HAL timers to embedded-time"



